3dprint/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('get_print/' , include('get_print.urls')),
]

get_print/urls.py
from django.contrib import admin
from django.urls import path 
from get_print import views

app_name = 'get_print'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('register', views.register_request, name='register'),
    path('login', views.login_request, name='login'),
    path('logout', views.logout_request, name='logout'),
    path('workspace', views.workspace, name='workspace'),
    path('parts', views.parts, name='parts'),
    path('parts/<int:part_id>', views.part, name='part'),
    path('upload_part', views.upload_part, name='upload_part'),
    path('orders', views.orders, name='orders'),
    path('quotes', views.quotes, name='quotes'),
    path('order-status', views.order_status, name='order_status'),
    path('projects', views.projects, name='projects'),
    path('materials', views.materials, name='materials'),
    path('technologies', views.technologies, name='technologies'),
]

give_print/urls.py
from django.urls import path 
from give_print import views

app_name = "give_print"

urlpatterns = [
    path("", views.home, name = 'home'),
    path("about", views.about, name = 'about'),
    path("register", views.register_request, name = 'register'),
    path("login", views.login_request, name = 'login'),
    path("logout", views.logout_request, name = 'logout'),
    path("dashboard", views.dashboard, name = 'dashboard'),
]

home/urls.py
from django.contrib import admin
from django.urls import path 
from home import views

urlpatterns = [
    path("", views.index, name = 'home'),
    path("about", views.about, name = 'about'),
    path("register", views.register, name = 'register'),
    path("contact", views.contact, name = 'supplier'),
    path("login", views.login, name = 'login'),
    
]

project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('get_print.urls')),
    path('supplier/', include('give_print.urls')),
    path('instant_quote/', include('instant_quote.urls')),
    path('chaining/', include('smart_selects.urls')),
]

training/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('home.urls')),
]

instant_quote/models.py
from django.db import models

# Create your models here.

# table for all parts
class Part(models.Model):
    part = models.FileField(upload_to='uploads')

    def __str__(self):
        return self.part.name

instant_quote/forms.py
from django.forms import ModelForm
from .models import Part
from project1.models import PrintSpecification, ShippingInfo


# Create your forms here.

# Form for uplading a part
class PartUploadForm(ModelForm):
	class Meta:
		model = Part
		fields = ["part"]

class PrintSpecificationForm(ModelForm):
	class Meta:
		model = PrintSpecification
		fields = ['units', 'resolution', 'process', 'material', 'colours', 'additional_info']

class ShippingInfoForm(ModelForm):
	class Meta:
		model = ShippingInfo
		fields = ['first_name', 'last_name', 'email', 'phone', 'address', 'pin_code', 'city']

instant_quote/views.py
from django.shortcuts import render
from .forms import PartUploadForm, PrintSpecificationForm, ShippingInfoForm
from project1.util import find_suppliers

# Create your views here.
def index(request):
    upload_form = PartUploadForm()
    specification_form = PrintSpecificationForm()
    shipping_info_form = ShippingInfoForm()
    suppliers = []
    if request.method == 'POST':
        PartUploadForm(request.POST, request.FILES).save()
        specification = PrintSpecificationForm(request.POST).save()
        ShippingInfoForm(request.POST).save()
        suppliers = find_suppliers(specification)
    return render(request, 'instant_quote/index.html', {'upload_form': upload_form, 'specification_form': specification_form, 'shipping_info_form': shipping_info_form, 'suppliers': suppliers})

instant_quote/templates/instant_quote/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      {% block title %} {% endblock %}
    </title>  
  </head>

  <body>

    {% include 'get_print/includes/messages.html' %}

    <h1>3D Printing</h1>
    <ul>
      <li>
        <a href="{% url 'give_print:home' %}">Become a supplier</a>
      </li>
      <br>
      <li>
        <a href="{% url 'get_print:home' %}">Home</a>
      </li>
      <li>
        <a href="{% url 'get_print:about' %}">About Us</a>
      </li>

      {% if user.is_authenticated %}

        <li>
          <a href="{% url 'get_print:workspace' %}">Workspace</a>
        </li>

        <li>
          <a href="{% url 'get_print:logout' %}">Logout</a>
        </li>

      {% else %}

        <li>
          <a href="{% url 'get_print:register' %}">Register</a>
        </li>
        <li>
          <a href="{% url 'get_print:login' %}">Login</a>
        </li>

      {% endif %}
      <li>
        <a href="{% url instant_quote:index' %}">Get Instant Quote</a>
      </li>
    </ul>
    {% block body  %}

    {% endblock %}

  </body>
</html>

instant_quote/templates/instant_quote/index.html
{% extends 'get_print/base.html' %}
{% load static %}


{% block body %}

    {% load crispy_forms_tags %}

    <div style="margin: 50px 0px 50px 0px; padding: 50px ;">
        <h1>Get Instant Quote</h1>
        <form action="{% url 'instant_quote:index' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
    
            <h2>Upload Part</h2>
            {{ upload_form|crispy }}
    
            <h2>Print Specifications</h2>
            {{ specification_form.media.js }}
            {{ specification_form|crispy }}
    
            <h2>Shipping Information</h2>
            {{ shipping_info_form|crispy }}
            <br>
            <input type="submit" value="Find suppliers">
    
            {% if suppliers %}
                <form action="{% url 'get_print:order_status' %}" method="GET">
                    {% csrf_token %}
                    {% for supplier in suppliers %}
                        <input type="radio" id='{{supplier.user.id}}' name='quote' value='{{supplier.user.id}}'>
                        <label for='{{supplier.user.id}}'>{{supplier.user.username}}</label>
                    {% endfor %}
                </form>
                <input type="submit" name="Place Order" value="Place Order">
            {% else %}
                <h1>No suppliers matched</h1>
            {% endif %}
        </form>
    </div>
        
{% endblock %}