3dprint/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('get_print/' , include('get_print.urls')),
]

give_print/urls.py
from django.urls import path 
from give_print import views

app_name = "give_print"

urlpatterns = [
    path("", views.home, name = 'home'),
    path("about", views.about, name = 'about'),
    path("register", views.register_request, name = 'register'),
    path("login", views.login_request, name = 'login'),
    path("logout", views.logout_request, name = 'logout'),
    path("dashboard", views.dashboard, name = 'dashboard'),
]

home/urls.py
from django.contrib import admin
from django.urls import path 
from home import views

urlpatterns = [
    path("", views.index, name = 'home'),
    path("about", views.about, name = 'about'),
    path("register", views.register, name = 'register'),
    path("contact", views.contact, name = 'supplier'),
    path("login", views.login, name = 'login'),
    
]

project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('get_print.urls')),
    path('supplier/', include('give_print.urls')),
    path('instant_quote/', include('instant_quote.urls')),
    path('chaining/', include('smart_selects.urls')),
]

training/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('home.urls')),
]

give_print/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import CharField

# Create your models here.

class Process(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Material(models.Model):
    name = models.CharField(max_length=100)
    processes = models.ManyToManyField(Process)

    def __str__(self):
        return self.name

class Colour(models.Model):
    name = models.CharField(max_length=50)
    materials = models.ManyToManyField(Material)
    
    def __str__(self):
        return self.name

class Printer(models.Model):
    make = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    process = models.ForeignKey(Process, on_delete=models.CASCADE, related_name='printers')
    build_volume = models.ForeignKey

    def __str__(self):
        return f"{self.make} {self.model}"

class Supplier(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company_name = models/CharField(max_length=100)
    printers = models.ManyToManyField(Printer, related_name='with_suppliers')
    materials = models.ManyToManyField(Material, related_name='with_suppliers')
    GSTIN = models.CharField(max_length=15)
    location = models.CharField(max_length=200)

    def __str__(self):
        return self.user.username

give_print/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

# Form for new user registration
class NewUserForm(UserCreationForm):
	#email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("first_name", "last_name", "username", "email", "password1", "password2")

give_print/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from .forms import NewUserForm

# Create your views here.
def home(request):
    return render(request, 'give_print/home.html')

def about(request):
    return render(request, 'give_print/about.html')

# Ask for user registration details and save it in database.
def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect('give_print:workspace')
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render (request=request, template_name="give_print/register.html", context={"register_form":form})

# Verify credentials and login user
def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect('give_print:workspace')
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name='give_print/login.html', context={'login_form':form})

# Logout user
@login_required
def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect('give_print:home')

def dashboard(request):
    pass

home/views.py
from django.shortcuts import  render, redirect
from .forms import NewUserForm
from django.contrib.auth import login
from django.contrib import messages
from datetime import datetime
from home.models import Contact, Newuser

# Create your views here.

def index(request):
    return render(request,'index.html')

def about(request):
    return render(request, 'about.html')

# Ask for user registration details and save it in database.
def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect("main:homepage")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render (request=request, template_name="register.html", context={"register_form":form})

# Verify credentialas and login user
def login(request):
    return render(request, 'login.html')

# Ask for supplier information and save it in databse.
def contact(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        contact = Contact(name = name, email=email, phone=phone, date=datetime.today())
        contact.save()

    
    return render(request, 'contact.html')

give_print/templates/give_print/about.html
{% extends 'give_print/base.html' %}

{% block title %} About {% endblock %}

{% block body %}
    <h1>About Us</h1>
    this is About page
{% endblock %}

give_print/templates/give_print/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      {% block title %} {% endblock %}
    </title>  
  </head>

  <body>

    {% include 'give_print/includes/messages.html' %}

    <h1>3D Printing</h1>
    <ul>
      <li>
        <a href="{% url 'give_print:home' %}">Home</a>
      </li>
      <li>
        <a href="{% url 'give_print:about' %}">About Us</a>
      </li>

      {% if user.is_authenticated %}

        <li>
          <a href="{% url 'give_print:dashboard' %}">Dashboard</a>
        </li>

        <li>
          <a href="{% url 'give_print:logout' %}">Logout</a>
        </li>

      {% else %}

        <li>
          <a href="{% url 'give_print:register' %}">Register</a>
        </li>
        <li>
          <a href="{% url 'give_print:login' %}">Login</a>
        </li>

      {% endif %}
    </ul>
    {% block body  %}

    {% endblock %}

  </body>
</html>

give_print/templates/give_print/home.html
{% extends 'give_print/base.html' %}

{% block body %}
<h1>Home</h1>
    this is homepage
{% endblock body %}

give_print/templates/give_print/login.html
{% extends "give_print/base.html" %}

{% block body %}      

{% load crispy_forms_tags %}

<!--Login--> 
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="{% url 'give_print:register' %}">Create an account</a>.</p>
</div>

{% endblock %}

give_print/templates/give_print/register.html
{% extends 'give_print/base.html' %}

{% block title %} User Sign Up{% endblock %}

{% block body %}
  
  {% load crispy_forms_tags %}         

  <!--Register--> 
  <div class="container py-5">
    <h1>Register</h1>
    <form method="POST">
      {% csrf_token %}
      {{ register_form|crispy }}                    
      <button class="btn btn-primary" type="submit">Register</button>
    </form>
    <p class="text-center">If you already have an account, <a href="{% url 'give_print:login' %}">login</a> instead.</p>
  </div>

{% endblock body %}