3dprint/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('get_print/' , include('get_print.urls')),
]

get_print/urls.py
from django.contrib import admin
from django.urls import path 
from get_print import views

app_name = 'get_print'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('register', views.register_request, name='register'),
    path('login', views.login_request, name='login'),
    path('logout', views.logout_request, name='logout'),
    path('workspace', views.workspace, name='workspace'),
    path('parts', views.parts, name='parts'),
    path('parts/<int:part_id>', views.part, name='part'),
    path('upload_part', views.upload_part, name='upload_part'),
    path('orders', views.orders, name='orders'),
    path('quotes', views.quotes, name='quotes'),
    path('order-status', views.order_status, name='order_status'),
    path('projects', views.projects, name='projects'),
    path('materials', views.materials, name='materials'),
    path('technologies', views.technologies, name='technologies'),
]

give_print/urls.py
from django.urls import path 
from give_print import views

app_name = "give_print"

urlpatterns = [
    path("", views.home, name = 'home'),
    path("about", views.about, name = 'about'),
    path("register", views.register_request, name = 'register'),
    path("login", views.login_request, name = 'login'),
    path("logout", views.logout_request, name = 'logout'),
    path("dashboard", views.dashboard, name = 'dashboard'),
]

home/urls.py
from django.contrib import admin
from django.urls import path 
from home import views

urlpatterns = [
    path("", views.index, name = 'home'),
    path("about", views.about, name = 'about'),
    path("register", views.register, name = 'register'),
    path("contact", views.contact, name = 'supplier'),
    path("login", views.login, name = 'login'),
    
]

instant_quote/urls.py
from django.urls import path 
from instant_quote import views

app_name = 'instant_quote'

urlpatterns = [
    path('', views.index, name = 'index'),
]

project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('get_print.urls')),
    path('supplier/', include('give_print.urls')),
    path('instant_quote/', include('instant_quote.urls')),
    path('chaining/', include('smart_selects.urls')),
]

training/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('home.urls')),
]

get_print/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

# table for all parts
class Part(models.Model):
    part = models.FileField(upload_to='uploads')

    def __str__(self):
        return self.part.name

# table for user data
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    parts = models.ManyToManyField(Part, blank=True, related_name='uploaded_by')

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def update_customer(sender, instance, created, **kwargs):
    if created:
        Customer.objects.create(user=instance)
    else:
        instance.customer.save()

get_print/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.html import TRAILING_PUNCTUATION_CHARS
from .models import Part
from project1.models import PrintSpecification, ShippingInfo


# Create your forms here.

# Form for new user registration
class NewUserForm(UserCreationForm):
	#email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("first_name", "last_name", "username", "email", "password1", "password2")


# Form for uplading a part
class PartUploadForm(ModelForm):
	class Meta:
		model = Part
		fields = ["part"]

class PrintSpecificationForm(ModelForm):
	class Meta:
		model = PrintSpecification
		fields = ['units', 'resolution', 'process', 'material', 'colours', 'additional_info']

class ShippingInfoForm(ModelForm):
	class Meta:
		model = ShippingInfo
		fields = ['first_name', 'last_name', 'email', 'phone', 'address', 'pin_code', 'city']

get_print/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from .forms import NewUserForm, PartUploadForm, PrintSpecificationForm
from .models import Part
from project1.util import find_suppliers

# Create your views here.

def home(request):
    return render(request,'get_print/home.html')

def about(request):
    return render(request, 'get_print/about.html')

# Ask for user registration details and save it in database.
def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect('get_print:workspace')
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render (request=request, template_name="get_print/register.html", context={"register_form":form})

# Verify credentials and login user
def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect('get_print:workspace')
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name='get_print/login.html', context={'login_form':form})

# Logout user
@login_required
def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect('get_print:home')

# User's workspace: Parts, orders, history, profile.
@login_required
def workspace(request):
    return render(request, 'get_print/workspace.html')

# Show all parts Customer has uploaded
@login_required
def parts(request):
    parts = request.user.customer.parts.all()
    return render(request, 'get_print/parts.html', {'parts': parts})

# Lets user upload the model to print
@login_required
def upload_part(request):
    if request.method == 'POST':
        uploaded_part = PartUploadForm(request.POST, request.FILES)
        if uploaded_part.is_valid():
            p = uploaded_part.save()
            request.user.customer.parts.add(p)
            return redirect('get_print:parts')
    form = PartUploadForm()
    return render(request, 'get_print/upload_part.html', {'part_upload_form': form})

@login_required
def orders(request):
    pass

@login_required
def part(request, part_id):
    part_name = Part.objects.get(id=part_id).part.name
    form = PrintSpecificationForm()
    return render(request, 'get_print/part.html', {'print_specification_form': form, 'part_name': part_name})

@login_required
def quotes(request):
    specification = PrintSpecificationForm(request.POST).save()
    suppliers = find_suppliers(specification)
    return render(request, 'get_print/quotes.html', {'suppliers': suppliers}) 

@login_required
def order_status(request):
    status = 'Order placed!'
    return render(request, 'get_print/order_status.html', {'status': status})

@login_required
def projects(request):
    return render(request, 'get_print/projects.html')

def materials(request):
    return render(request, 'get_print/materials.html')

def technologies(request):
    return render(request, 'get_print/technologies.html')

home/views.py
from django.shortcuts import  render, redirect
from .forms import NewUserForm
from django.contrib.auth import login
from django.contrib import messages
from datetime import datetime
from home.models import Contact, Newuser

# Create your views here.

def index(request):
    return render(request,'index.html')

def about(request):
    return render(request, 'about.html')

# Ask for user registration details and save it in database.
def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect("main:homepage")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render (request=request, template_name="register.html", context={"register_form":form})

# Verify credentialas and login user
def login(request):
    return render(request, 'login.html')

# Ask for supplier information and save it in databse.
def contact(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        contact = Contact(name = name, email=email, phone=phone, date=datetime.today())
        contact.save()

    
    return render(request, 'contact.html')

get_print/templates/get_print/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>
      {% block title %} {% endblock %}
    </title>
    <meta content="" name="description">
    <meta content="" name="keywords">
  
    <!-- Favicons -->
    <link href="images.png" rel="icon">
    <link href="images.png" rel="apple-touch-icon">
  
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet">
  
    <!-- Vendor CSS Files -->
    <link href="{% static 'get_print/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'get_print/assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
    <link href="{% static 'get_print/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'get_print/assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'get_print/assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
    <link href="{% static 'get_print/assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'get_print/assets/vendor/aos/aos.css' %}" rel="stylesheet">
  
    <!-- Template Main CSS File -->
    <link href="{% static 'get_print/assets/css/style.css' %}" rel="stylesheet">

    <!-- Template instant_quote CSS File -->
    <link href="{% static 'instant_quote/style.css' %}" rel="stylesheet">
  
  </head>

  <body>

    {% include 'get_print/includes/messages.html' %}

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top ">
      <div class="container d-flex align-items-center justify-content-between">
  
        <h1 class="logo"><a href="{% url 'get_print:home' %}">3D<span>PRINTING</span></a></h1>
        <!-- Uncomment below if an image logo is to be used -->
        <!--a href="index.html" class="logo"><img src="{% static 'get_print/assets/img/logo.png' %}" alt="" class="img-fluid"></a-->
  
        <nav class="nav-menu d-none d-lg-block">
          <ul>
            <!--li class="active"><a href="#hero">Home</a></li-->
            <li><a href="{% url 'get_print:about' %}">About</a></li>
            <li><a href="{% url 'get_print:materials' %}">Materials</a></li>
            <li class="drop-down"><a href="{% url 'get_print:technologies' %}">Technology</a>
              <ul>
                <li><a href="{% url 'get_print:technologies' %}#fdm">FDM</a></li>
                <li><a href="{% url 'get_print:technologies' %}#dmls">DMLS</a></li>
                <li><a href="{% url 'get_print:technologies' %}#mjf">MJF</a></li>
                <li><a href="{% url 'get_print:technologies' %}#sls">SLS</a></li>
                <li><a href="{% url 'get_print:technologies' %}#sla">SLA</a></li>
              </ul>
            </li>
            <li><a href="{% url 'get_print:home' %}#team">Team</a></li>
            <li><a href="supplier/supplierhome.html">Become a Supplier</a></li>
            <li><a href="{% url 'get_print:home' %}#contact">Contact</a></li>
          </ul>
        </nav><!-- .nav-menu -->
        <a style="margin-left:20px;" href="{% url 'instant_quote:index' %}" class="get-started-btn scrollto">Get Your Quote</a>
        <li style="margin-left: 20px;" class="nav-item pl-2 mb-2 mb-md-0 d-md-none d-xl-inline-block">
          <a href="login/login.html" type="button" class="get-started-btn scrollto">SIGN UP</a>
        </li>
      </div>
    </header><!-- End Header -->  

    <section style="display: none;">
      <h1>3D Printing</h1>
      <ul>
        <li>
          <a href="{% url 'give_print:home' %}">Become a supplier</a>
        </li>
        <br>
        <li>
          <a href="{% url 'get_print:home' %}">Home</a>
        </li>
        <li>
          <a href="{% url 'get_print:about' %}">About Us</a>
        </li>

        {% if user.is_authenticated %}

          <li>
            <a href="{% url 'get_print:workspace' %}">Workspace</a>
          </li>

          <li>
            <a href="{% url 'get_print:logout' %}">Logout</a>
          </li>

        {% else %}

          <li>
            <a href="{% url 'get_print:register' %}">Register</a>
          </li>
          <li>
            <a href="{% url 'get_print:login' %}">Login</a>
          </li>

        {% endif %}
        <li>
          <a href="{% url 'instant_quote:index' %}">Get Instant Quote</a>
        </li>
      </ul>
      </section>

    
    {% block body  %}

    {% endblock %}

    <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>
    <div id="preloader"></div>
    
    <!-- Vendor JS Files -->
    <script src="{% static 'get_print/assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'get_print/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'get_print/assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'get_print/assets/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'get_print/assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'get_print/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'get_print/assets/vendor/venobox/venobox.min.js' %}"></script>
    <script src="{% static 'get_print/assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'get_print/assets/vendor/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'get_print/assets/vendor/aos/aos.js' %}"></script>
  
    <!-- Template Main JS File -->
    <script src="{% static 'get_print/assets/js/main.js' %}"></script>
  
  </body>
</html>

get_print/templates/get_print/login.html
{% extends "get_print/base.html" %}

{% block body %}      

{% load crispy_forms_tags %}

<!--Login--> 
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="{% url 'get_print:register' %}">Create an account</a>.</p>
</div>

{% endblock %}

get_print/templates/get_print/order_status.html
{% extends 'get_print/base.html' %}

{% block body %}
    <h1>{{ status }}</h1>
{% endblock %}

get_print/templates/get_print/part.html
{% extends 'get_print/base.html' %}

{% block body %}
    <h1>{{part_name}}</h1>
    <br>
    <h2>Specifications</h2>
    <form action="{% url 'get_print:quotes' %}" method="POST">
        {% csrf_token %}
        {{ print_specification_form }}
        <input type="submit" name='Get Quotes' value='Get Quotes'>
    </form>
{% endblock %}

get_print/templates/get_print/parts.html
{% extends 'get_print/base.html' %}

{% block body %}
    <ul>
        {% for part in parts %}
        <li>
            <a href="{% url 'get_print:part' part.id %}">{{ part }}</a>
        </li>
        {% endfor %}
    </ul>
    

    <a href="{% url 'get_print:upload_part' %}">Upload Part</a>

{% endblock %}

get_print/templates/get_print/projects.html
{% extends 'get_print/base.html' %}

{% block body %}
    <ul>
        {% for project in projects %}
        <li>
            <a href="{% url 'get_print:project' %}">{{ project }}</a>
        </li>
        {% endfor %}
    </ul>
    

    <a href="{% url 'get_print:upload_part' %}">Upload Part</a>

{% endblock %}

get_print/templates/get_print/quotes.html
{% extends 'get_print/base.html' %}

{% block body %}
    {% if suppliers %}
        <form action="{% url 'get_print:order_status' %}" method="GET">
            {% csrf_token %}
            {% for supplier in suppliers %}
                <input type="radio" id='{{supplier.user.id}}' name='quote' value='{{supplier.user.id}}'>
                <label for='{{supplier.user.id}}'>{{supplier.user.username}}</label>
            {% endfor %}
        </form>
        <input type="submit" name="Place Order" value="Place Order">
    {% else %}
        <h1>No suppliers matched</h1>
    {% endif %}
{% endblock %}

get_print/templates/get_print/register.html
{% extends 'get_print/base.html' %}

{% block title %} User Sign Up{% endblock %}

{% block body %}
  
  {% load crispy_forms_tags %}         

  <!--Register--> 
  <div class="container py-5">
    <h1>Register</h1>
    <form method="POST">
      {% csrf_token %}
      {{ register_form|crispy }}                    
      <button class="btn btn-primary" type="submit">Register</button>
    </form>
    <p class="text-center">If you already have an account, <a href="{% url 'get_print:login' %}">login</a> instead.</p>
  </div>

{% endblock body %}

get_print/templates/get_print/upload_part.html
{% extends "get_print/base.html" %}
{% load crispy_forms_tags %}

{% block body %}

<div class="input-group">
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ part_upload_form|crispy }}
    <button class="btn btn-primary" type="submit">Submit</button>
</form>
</div>


{% endblock %}

get_print/templates/get_print/workspace.html
{% extends 'get_print/base.html' %}

{% block body %}
    <h1>Workspace</h1>
    <h2>Welcome, {{user}}</h2>
    <a href="{% url 'get_print:parts' %}">Parts</a>
    <a href="{% url 'get_print:orders' %}">Orders</a>
{% endblock %}